# Generated by Django 5.2.1 on 2025-05-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SesionPomodoro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('duracion_minutos', models.PositiveIntegerField(default=25)),
                ('completada', models.BooleanField(default=False)),
            ],
        ),
    ]
