# Generated by Django 5.2.1 on 2025-05-18 23:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
        ('pomodoro', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesionpomodoro',
            name='completada',
        ),
        migrations.RemoveField(
            model_name='sesionpomodoro',
            name='duracion_minutos',
        ),
        migrations.RemoveField(
            model_name='sesionpomodoro',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='sesionpomodoro',
            name='usuario',
        ),
        migrations.AddField(
            model_name='sesionpomodoro',
            name='duracion',
            field=models.IntegerField(default=25, help_text='Duración total en minutos'),
        ),
        migrations.AddField(
            model_name='sesionpomodoro',
            name='fin',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sesionpomodoro',
            name='inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sesionpomodoro',
            name='pausas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sesionpomodoro',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pomodoros', to='perfil.perfil'),
        ),
        migrations.AddField(
            model_name='sesionpomodoro',
            name='tipo',
            field=models.CharField(choices=[('foco', 'Foco'), ('descanso_corto', 'Descanso Corto'), ('descanso_largo', 'Descanso Largo')], default='foco', max_length=20),
        ),
    ]
