# Generated by Django 5.2.1 on 2025-05-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0003_remove_sesionpomodoro_completada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesionpomodoro',
            name='fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
