# Generated by Django 5.2.1 on 2025-05-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0004_alter_sesionpomodoro_fin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPomodoro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('foco_min', models.IntegerField(default=25)),
                ('descanso_corto_min', models.IntegerField(default=5)),
                ('descanso_largo_min', models.IntegerField(default=15)),
                ('ciclos', models.IntegerField(default=4)),
            ],
        ),
    ]
