# Generated by Django 5.2.1 on 2025-05-24 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
        ('pomodoro', '0005_configuracionpomodoro'),
        ('winds', '0004_wind_focus_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionpomodoro',
            name='wind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_pomodoro', to='winds.wind'),
        ),
        migrations.AlterField(
            model_name='sesionpomodoro',
            name='duracion',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='sesionpomodoro',
            name='perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pomodoros', to='perfil.perfil'),
            preserve_default=False,
        ),
    ]
