# Generated by Django 5.2.1 on 2025-05-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0006_sesionpomodoro_wind_alter_sesionpomodoro_duracion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionpomodoro',
            name='config_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
