# Generated by Django 5.2.1 on 2025-05-25 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0007_sesionpomodoro_config_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesionpomodoro',
            name='duracion',
            field=models.FloatField(default=0),
        ),
    ]
