# Generated by Django 5.2.1 on 2025-05-18 23:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
        ('tareas', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='completada',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='fecha_limite',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='prioridad',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='usuario',
        ),
        migrations.AddField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('completada', 'Completada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tarea',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='perfil.perfil'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
