# Generated by Django 5.2.1 on 2025-05-24 15:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_tarea_descripcion_tarea_fecha_limite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
