# Generated by Django 5.2.1 on 2025-05-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0005_alter_tarea_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='completada',
            field=models.BooleanField(default=False),
        ),
    ]
