# Generated by Django 5.2.1 on 2025-05-18 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_creados', to='perfil.perfil')),
                ('usuarios', models.ManyToManyField(blank=True, related_name='grupos_pertenecientes', to='perfil.perfil')),
            ],
        ),
    ]
