# Generated by Django 5.2.1 on 2025-05-18 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0003_remove_nota_fecha_creacion_remove_nota_titulo_and_more'),
        ('perfil', '0001_initial'),
        ('tareas', '0003_remove_tarea_categoria_remove_tarea_completada_and_more'),
        ('winds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wind',
            old_name='nombre',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='wind',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='wind',
            name='usuario',
        ),
        migrations.AddField(
            model_name='wind',
            name='notas',
            field=models.ManyToManyField(blank=True, to='notas.nota'),
        ),
        migrations.AddField(
            model_name='wind',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winds', to='perfil.perfil'),
        ),
        migrations.AddField(
            model_name='wind',
            name='tareas',
            field=models.ManyToManyField(blank=True, to='tareas.tarea'),
        ),
        migrations.AlterField(
            model_name='wind',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
