# Generated by Django 5.2.1 on 2025-05-24 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0005_configuracionpomodoro'),
        ('winds', '0002_rename_nombre_wind_titulo_remove_wind_creado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wind',
            name='pomodoro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winds', to='pomodoro.configuracionpomodoro'),
        ),
    ]
