# Generated by Django 5.2.1 on 2025-05-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winds', '0003_wind_pomodoro'),
    ]

    operations = [
        migrations.AddField(
            model_name='wind',
            name='focus_mode',
            field=models.BooleanField(default=True, help_text='¿Usar este Wind en modo Focus (Pomodoro incluido)?'),
        ),
    ]
