# Generated by Django 5.2.1 on 2025-05-28 16:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winds', '0004_wind_focus_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wind',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
