# Generated by Django 5.2.1 on 2025-05-18 23:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_initial'),
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='usuario',
        ),
        migrations.AddField(
            model_name='nota',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='nota',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='perfil.perfil'),
        ),
    ]
