# Generated by Django 5.2.1 on 2025-05-22 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0003_remove_nota_fecha_creacion_remove_nota_titulo_and_more'),
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nota',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterField(
            model_name='nota',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='perfil.perfil'),
            preserve_default=False,
        ),
    ]
