# Generated by Django 5.2.1 on 2025-05-28 16:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0004_alter_nota_options_alter_nota_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
